### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by nCore** [n3r4zzurr0/svg-spinners#3]
what is the license of `svg-spinners` library?

would be good to know and also create a `LICENSE` file for everyone interested because this looks amazing

**Comment by nCore** [comment]
oh, right now I see `LICENSE` file but not as attached to the repo - sorry - my mistake

**Comment by Perpetual11** [comment]
It  keeps on spinning..I tried to disconnect cable .but the is no such change on spinning

**Comment by Perpetual11** [comment]
I appreciate your kindness and generosity of spirit and fair
